-- ==============================================================================
-- IMPORT EXTERNAL DATA (from dados.csv.csv)
-- ==============================================================================

INSERT INTO public.participants (registration, name, email, network_login, cargo, supervisor, coordinator, manager, hierarchy_level, is_active)
VALUES
  ('226610', 'AMANDA LIMA LINO', 'a.amanda.lino@aec.com.br', 'a.amanda.lino', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('355042', 'AMANDA MARIA LIMA PRAXEDES', 'amanda.praxedes@aec.com.br', 'amanda.praxedes', 'INSTRUTOR DE TREINAMENTO', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('359193', 'ANA CAROLINA SILVA DOS SANTOS', 'ana.casantos@aec.com.br', 'ana.casantos', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('394527', 'ANA PAULA SANTOS FERREIRA', 'ana.psferreira@aec.com.br', 'ana.psferreira', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('323526', 'BRITNEN RODRIGUES DA SILVA', 'britnen.silva@aec.com.br', 'britnen.silva', 'INSTRUTOR DE TREINAMENTO', 'SILVIA RAFAELA SANTOS SILVA', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('425718', 'BRUCE NILTON LINS DE ALBUQUERQUE', 'bruce.albuquerque@aec.com.br', 'bruce.albuquerque', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('339297', 'BRUNA GABRIELA SILVA ALCANTARA', 'bruna.salcantara@aec.com.br', 'bruna.salcantara', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('277064', 'BRUNA WERDICHELE DOS SANTOS FARIAS', 'a.bruna.farias@aec.com.br', 'a.bruna.farias', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('328279', 'BRUNO DOMINGOS LEAO SILVA BARBOSA', 'bruno.sbarbosa@aec.com.br', 'bruno.sbarbosa', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('188595', 'CAIO MANOEL LIMA DA SILVA', 'a.caio.silva@aec.com.br', 'a.caio.silva', 'INSTRUTOR DE TREINAMENTO', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('414143', 'CARLOS EMANUEL GONZAGA DA SILVA', 'carlos.emanuel@aec.com.br', 'carlos.emanuel', 'INSTRUTOR DE TREINAMENTO', NULL, 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('236566', 'CARLOS FELIPE SILVA DOS SANTOS', 'a.carlos.fsantos@aec.com.br', 'a.carlos.fsantos', 'INSTRUTOR DE TREINAMENTO', 'JULIO CESAR ALVES DA SILVA SANTOS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('225575', 'CESAR DE ASSIS DOS SANTOS', 'a.cesar.santos@aec.com.br', 'a.cesar.santos', 'ANALISTA DE CONTEUDO JUNIOR', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('179893', 'EDUARDO BARROS DOS SANTOS', 'a.eduardo.santos@aec.com.br', 'a.eduardo.santos', 'INSTRUTOR DE TREINAMENTO', 'JULIO CESAR ALVES DA SILVA SANTOS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('268126', 'ELIELZA KAROLYNE DOS SANTOS', 'a.elielza.santos@aec.com.br', 'a.elielza.santos', 'SUPERVISOR DE PESSOAS JUNIOR', NULL, 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'supervisor', true),
  ('311103', 'ELISON ELLAN BARBOSA DOS SANTOS', 'elison.ellan@aec.com.br', 'elison.ellan', 'ANALISTA DE CONTEUDO JUNIOR', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('282575', 'EVYLA SAMYLLA DOS SANTOS', 'a.evyla.samylla@aec.com.br', 'a.evyla.samylla', 'INSTRUTOR DE TREINAMENTO', 'SILVIA RAFAELA SANTOS SILVA', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('316712', 'FELIPE CORDEIRO SANTOS', 'felipe.csantos@aec.com.br', 'felipe.csantos', 'AUXILIAR DE PESSOAS', NULL, 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('376353', 'FRANCIANE SEVERO DA SILVA', 'franciane.ssevero@aec.com.br', 'franciane.ssevero', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('418056', 'GABRIEL VICENTE GOMES DOS SANTOS', 'gabriel.vsantos@aec.com.br', 'gabriel.vsantos', 'INSTRUTOR DE TREINAMENTO', 'JULIO CESAR ALVES DA SILVA SANTOS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('261852', 'GABRIELLA KELLY DA SILVA', 'a.gabriella.ksilva@aec.com.br', 'a.gabriella.ksilva', 'INSTRUTOR DE TREINAMENTO', 'JULIO CESAR ALVES DA SILVA SANTOS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('452013', 'GRACYELLE AZARIAS NUNES DA SILVA', 'gracyelle.azarias@aec.com.br', 'gracyelle.azarias', 'ANALISTA DE CONTEUDO JUNIOR', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('316800', 'GUSTAVO VIEIRA PIANCO DE ALMEIDA', 'gustavo.pianco@aec.com.br', 'gustavo.pianco', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('427417', 'IRIS SILVA DE OLIVEIRA', 'iris.oliveira@aec.com.br', 'iris.oliveira', 'INSTRUTOR DE TREINAMENTO', NULL, 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('235630', 'IVANNEIDE SANTOS OLIVEIRA', 'a.ivanneide.oliveira@aec.com.br', 'a.ivanneide.oliveira', 'INSTRUTOR DE TREINAMENTO', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('261064', 'IZAURA DE ARAUJO BEZERRA', 'a.izaura.bezerra@aec.com.br', 'a.izaura.bezerra', 'COORDENADOR DE PESSOAS II', NULL, 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'coordenador', true),
  ('393084', 'JACIANE DA SILVA EVANGELISTA', 'jaciane.evangelista@aec.com.br', 'jaciane.evangelista', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('263470', 'JAKSWELL FERNANDES DA SILVA', 'a.jakswell.silva@aec.com.br', 'a.jakswell.silva', 'ANALISTA DE CONTEUDO JUNIOR', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('261887', 'JAMMERSON MICHAELL DOS SANTOS OLIVEIRA', 'a.jammerson.oliveira@aec.com.br', 'a.jammerson.oliveira', 'ANALISTA DE CONTEUDO JUNIOR', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('285823', 'JEANE MOREIRA BATISTA', 'a.jeane.batista@aec.com.br', 'a.jeane.batista', 'INSTRUTOR DE TREINAMENTO', 'SILVIA RAFAELA SANTOS SILVA', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('321952', 'JHENNIFER SOARES RAMOS', 'jhennifer.ramos@aec.com.br', 'jhennifer.ramos', 'INSTRUTOR DE TREINAMENTO', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('281595', 'JOAO LUCAS FERREIRA CANDIDO', 'a.joao.candido@aec.com.br', 'a.joao.candido', 'ASSISTENTE DE PESSOAS', NULL, 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('348458', 'JOAO VITOR RODRIGUES DOS SANTOS', 'joao.rodriguess@aec.com.br', 'joao.rodriguess', 'INSTRUTOR DE TREINAMENTO', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('236966', 'JOHN LENNON DA SILVA SANTOS', 'a.john.santos@aec.com.br', 'a.john.santos', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('134187', 'JONATHAN LINS DA SILVA', 'jonathan.silva@aec.com.br', 'jonathan.silva', 'GERENTE DE PESSOAS III', NULL, 'JONATHAN LINS DA SILVA', 'Jonathan Lins da Silva', 'gerente', true),
  ('325729', 'JORDANA KAROLLYNE SANTOS QUEIROZ', 'jordana.queiroz@aec.com.br', 'jordana.queiroz', 'INSTRUTOR DE TREINAMENTO', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('211199', 'JULIO CESAR ALVES DA SILVA SANTOS', 'a.julio.cesar@aec.com.br', 'a.julio.cesar', 'SUPERVISOR DE PESSOAS JUNIOR', NULL, 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'supervisor', true),
  ('227625', 'KELCIANE CAVALCANTE DE LIMA', 'kelciane.lima@aec.com.br', 'kelciane.lima', 'COORDENADOR DE PESSOAS I', NULL, 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'coordenador', true),
  ('225775', 'KELDES SILVA DE ARAUJO', 'a.keldes.araujo@aec.com.br', 'a.keldes.araujo', 'INSTRUTOR DE TREINAMENTO', 'ELIELZA KAROLYNE DOS SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('263147', 'LETICIA SANTOS GOMES', 'a.leticia.sgomes@aec.com.br', 'a.leticia.sgomes', 'INSTRUTOR DE TREINAMENTO', 'SILVIA RAFAELA SANTOS SILVA', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('299268', 'LORRANNY WITORIA LEITE DOS SANTOS', 'a.lorranny.wsantos@aec.com.br', 'a.lorranny.wsantos', 'INSTRUTOR DE TREINAMENTO', 'JULIO CESAR ALVES DA SILVA SANTOS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('344118', 'LUAN HENRIQUE GOMES LUCENA', 'luan.lucena@aec.com.br', 'luan.lucena', 'INSTRUTOR DE TREINAMENTO', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('390247', 'LUIS HENRIQUE AMORIM DA SILVA', 'a.luis.asilva@aec.com.br', 'a.luis.asilva', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('307241', 'MARIA ALICE MIRANDA DA SILVA', 'maria.alice@aec.com.br', 'maria.alice', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('157727', 'MARIA AMANDA DOS SANTOS', 'a.maria.amanda@aec.com.br', 'a.maria.amanda', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('225756', 'MARIA CLARA DA SILVA SANTOS', 'a.maria.clara@aec.com.br', 'a.maria.clara', 'SUPERVISOR DE PESSOAS JUNIOR', NULL, 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'supervisor', true),
  ('452015', 'MARIA CLARA FRANCA DA SILVA', 'maria.clfranca@aec.com.br', 'maria.clfranca', 'ANALISTA DE CONTEUDO JUNIOR', NULL, 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('281726', 'MARIANA PEREIRA VERAS', 'a.mariana.veras@aec.com.br', 'a.mariana.veras', 'SUPERVISOR DE PESSOAS JUNIOR', NULL, 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'supervisor', true),
  ('238470', 'MAYENNY DE ALMEIDA SANTOS', 'a.mayenny.santos@aec.com.br', 'a.mayenny.santos', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('461576', 'MICKAEL BANDEIRA DA SILVA', 'mickael.bandeira@aec.com.br', 'mickael.bandeira', 'ANALISTA DE CONTEUDO JUNIOR', NULL, 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('387998', 'MIKAELLY TENORIO DA SILVA', 'mikaelly.tenorio@aec.com.br', 'mikaelly.tenorio', 'INSTRUTOR DE TREINAMENTO', 'JULIO CESAR ALVES DA SILVA SANTOS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('294911', 'MURILLO HENRIQUE ALMEIDA DE SOUZA', 'a.murillo.asouza@aec.com.br', 'a.murillo.asouza', 'INSTRUTOR DE TREINAMENTO', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('324648', 'MYKAELLI DARLA FRANCISCA DA SILVA', 'mykaelli.silva@aec.com.br', 'mykaelli.silva', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('321356', 'PALOMA CAROLINE SILVA ARAUJO', 'paloma.saraujo@aec.com.br', 'paloma.saraujo', 'INSTRUTOR DE TREINAMENTO', 'ELIELZA KAROLYNE DOS SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('286898', 'PAULINA INACIO GOMES NUNES', 'nu.paulina.gomes@aec.com.br', 'nu.paulina.gomes', 'INSTRUTOR DE TREINAMENTO', NULL, 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('333076', 'PAULO GUILHERME DOS ANJOS CASTILIANI', 'paulo.castiliani@aec.com.br', 'paulo.castiliani', 'SUPERVISOR DE OPERACAO', NULL, 'WILLAMES VIEIRA DE OLIVEIRA JUNIOR', 'Jonathan Lins da Silva', 'supervisor', true),
  ('417527', 'PAULO HENRIQUE TENORIO LIMA', 'paulo.tenorio@aec.com.br', 'paulo.tenorio', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('210515', 'RAYLA ALVES DOS SANTOS', 'a.rayla.santos@aec.com.br', 'a.rayla.santos', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('155494', 'RENATA MARIA DA SILVA', 'a.renata.maria@aec.com.br', 'a.renata.maria', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('326416', 'ROBERIO ALVES SANTANA JUNIOR', 'roberio.junior@aec.com.br', 'roberio.junior', 'ANALISTA DE PESSOAS JUNIOR', NULL, 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('359028', 'RONALDO NOBERTO DOS SANTOS', 'ronaldo.noberto@aec.com.br', 'ronaldo.noberto', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('179844', 'SAMUEL PEDRO DOS SANTOS', 'a.samuel.pedro@aec.com.br', 'a.samuel.pedro', 'ANALISTA DE PESSOAS JUNIOR', NULL, 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('368774', 'SILVIA RAFAELA SANTOS SILVA', 'silvia.silva@aec.com.br', 'silvia.silva', 'SUPERVISOR DE PESSOAS JUNIOR', NULL, 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'supervisor', true),
  ('268142', 'SILVIO MANUEL SILVA SANTOS', 'a.silvio.santos@aec.com.br', 'a.silvio.santos', 'ANALISTA DE CONTEUDO JUNIOR', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('425703', 'TAISE CORREIA DE LIRA', 'taise.lira@aec.com.br', 'taise.lira', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('260797', 'VALDERLAN LACERDA DOS SANTOS', 'a.valderlan.santos@aec.com.br', 'a.valderlan.santos', 'ANALISTA DE PESSOAS PLENO', NULL, 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('143234', 'VANESSA FERREIRA DOS SANTOS', 'a.vanessa.dsantos@aec.com.br', 'a.vanessa.dsantos', 'INSTRUTOR DE TREINAMENTO', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('260648', 'VINICIUS GABRIEL SILVA OLIVEIRA', 'a.vinicius.oliveira@aec.com.br', 'a.vinicius.oliveira', 'INSTRUTOR DE TREINAMENTO', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('314018', 'VITOR RAFAEL BARBOSA DE FARIAS', 'vitor.farias@aec.com.br', 'vitor.farias', 'INSTRUTOR DE TREINAMENTO', 'MARIA CLARA DA SILVA SANTOS', 'KELCIANE CAVALCANTE DE LIMA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('306064', 'WELLINGTON NASCIMENTO DA SILVA', 'a.wellington.nsilva@aec.com.br', 'a.wellington.nsilva', 'INSTRUTOR DE TREINAMENTO', 'JULIO CESAR ALVES DA SILVA SANTOS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true),
  ('262756', 'YARA BENEDITA DOS SANTOS SILVA', 'a.yara.ssilva@aec.com.br', 'a.yara.ssilva', 'ANALISTA DE CONTEUDO PLENO', 'MARIANA PEREIRA VERAS', 'IZAURA DE ARAUJO BEZERRA', 'Jonathan Lins da Silva', 'colaborador', true)
ON CONFLICT (registration) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  network_login = EXCLUDED.network_login,
  cargo = EXCLUDED.cargo,
  supervisor = EXCLUDED.supervisor,
  coordinator = EXCLUDED.coordinator,
  manager = EXCLUDED.manager,
  hierarchy_level = EXCLUDED.hierarchy_level,
  updated_at = now();

-- 2. Insert Test Results
INSERT INTO public.test_results (registration, name, email, score_d, score_i, score_s, score_c, dominant_profile, completed_at)
VALUES
  ('226610', 'AMANDA LIMA LINO', 'a.amanda.lino@aec.com.br', 9, 2, 10, 9, 'S', '2025-11-10 10:01:49'),
  ('355042', 'AMANDA MARIA LIMA PRAXEDES', 'amanda.praxedes@aec.com.br', 9, 10, 8, 3, 'I', '2025-11-10 09:45:47'),
  ('359193', 'ANA CAROLINA SILVA DOS SANTOS', 'ana.casantos@aec.com.br', 10, 3, 11, 6, 'S', '2025-11-10 10:08:14'),
  ('394527', 'ANA PAULA SANTOS FERREIRA', 'ana.psferreira@aec.com.br', 5, 10, 8, 7, 'I', '2025-11-10 09:19:43'),
  ('323526', 'BRITNEN RODRIGUES DA SILVA', 'britnen.silva@aec.com.br', 4, 7, 13, 6, 'S', '2025-11-10 09:24:28'),
  ('425718', 'BRUCE NILTON LINS DE ALBUQUERQUE', 'bruce.albuquerque@aec.com.br', 17, 8, 1, 4, 'D', '2025-11-10 09:19:58'),
  ('339297', 'BRUNA GABRIELA SILVA ALCANTARA', 'bruna.salcantara@aec.com.br', 1, 6, 13, 10, 'S', '2025-11-10 10:12:03'),
  ('277064', 'BRUNA WERDICHELE DOS SANTOS FARIAS', 'a.bruna.farias@aec.com.br', 4, 10, 11, 5, 'S', '2025-11-10 09:48:36'),
  -- Bruno Domingos: Pendente
  ('188595', 'CAIO MANOEL LIMA DA SILVA', 'a.caio.silva@aec.com.br', 1, 10, 12, 7, 'S', '2025-11-10 09:47:02'),
  ('414143', 'CARLOS EMANUEL GONZAGA DA SILVA', 'carlos.emanuel@aec.com.br', 5, 6, 7, 12, 'C', '2025-11-10 09:42:26'),
  ('236566', 'CARLOS FELIPE SILVA DOS SANTOS', 'a.carlos.fsantos@aec.com.br', 8, 6, 11, 5, 'S', '2025-11-10 09:28:13'),
  ('225575', 'CESAR DE ASSIS DOS SANTOS', 'a.cesar.santos@aec.com.br', 4, 4, 12, 10, 'S', '2025-11-10 09:30:29'),
  ('179893', 'EDUARDO BARROS DOS SANTOS', 'a.eduardo.santos@aec.com.br', 11, 3, 4, 12, 'C', '2025-11-11 10:29:32'),
  ('268126', 'ELIELZA KAROLYNE DOS SANTOS', 'a.elielza.santos@aec.com.br', 6, 12, 4, 8, 'I', '2025-11-10 09:26:35'),
  ('311103', 'ELISON ELLAN BARBOSA DOS SANTOS', 'elison.ellan@aec.com.br', 1, 6, 12, 11, 'S', '2025-11-10 09:34:44'),
  ('282575', 'EVYLA SAMYLLA DOS SANTOS', 'a.evyla.samylla@aec.com.br', 7, 11, 9, 3, 'I', '2025-11-10 10:03:12'),
  ('316712', 'FELIPE CORDEIRO SANTOS', 'felipe.csantos@aec.com.br', 6, 7, 10, 7, 'S', '2025-11-10 09:37:36'),
  ('376353', 'FRANCIANE SEVERO DA SILVA', 'franciane.ssevero@aec.com.br', 8, 18, 1, 3, 'I', '2025-11-10 09:48:10'),
  ('418056', 'GABRIEL VICENTE GOMES DOS SANTOS', 'gabriel.vsantos@aec.com.br', 5, 9, 6, 10, 'C', '2025-11-10 09:20:37'),
  ('261852', 'GABRIELLA KELLY DA SILVA', 'a.gabriella.ksilva@aec.com.br', 12, 16, 1, 1, 'I', '2025-11-10 09:24:55'),
  ('452013', 'GRACYELLE AZARIAS NUNES DA SILVA', 'gracyelle.azarias@aec.com.br', 6, 12, 7, 5, 'I', '2025-11-10 14:15:09'),
  ('316800', 'GUSTAVO VIEIRA PIANCO DE ALMEIDA', 'gustavo.pianco@aec.com.br', 13, 4, 3, 10, 'D', '2025-11-10 10:05:56'),
  ('427417', 'IRIS SILVA DE OLIVEIRA', 'iris.oliveira@aec.com.br', 4, 4, 9, 13, 'C', '2025-11-10 09:44:31'),
  ('235630', 'IVANNEIDE SANTOS OLIVEIRA', 'a.ivanneide.oliveira@aec.com.br', 8, 13, 6, 3, 'I', '2025-11-10 09:27:33'),
  ('261064', 'IZAURA DE ARAUJO BEZERRA', 'a.izaura.bezerra@aec.com.br', 18, 9, 3, 0, 'D', '2025-11-10 10:09:31'),
  ('393084', 'JACIANE DA SILVA EVANGELISTA', 'jaciane.evangelista@aec.com.br', 1, 14, 10, 5, 'I', '2025-11-10 10:01:51'),
  ('263470', 'JAKSWELL FERNANDES DA SILVA', 'a.jakswell.silva@aec.com.br', 5, 3, 3, 19, 'C', '2025-11-13 17:52:13'),
  ('261887', 'JAMMERSON MICHAELL DOS SANTOS OLIVEIRA', 'a.jammerson.oliveira@aec.com.br', 8, 9, 6, 7, 'I', '2025-11-11 10:45:10'),
  ('285823', 'JEANE MOREIRA BATISTA', 'a.jeane.batista@aec.com.br', 1, 8, 11, 10, 'S', '2025-11-10 10:22:48'),
  ('321952', 'JHENNIFER SOARES RAMOS', 'jhennifer.ramos@aec.com.br', 6, 20, 3, 1, 'I', '2025-11-10 10:12:58'),
  ('281595', 'JOAO LUCAS FERREIRA CANDIDO', 'a.joao.candido@aec.com.br', 8, 10, 8, 4, 'I', '2025-11-10 09:15:39'),
  ('348458', 'JOAO VITOR RODRIGUES DOS SANTOS', 'joao.rodriguess@aec.com.br', 2, 5, 10, 13, 'C', '2025-11-10 10:00:48'),
  ('236966', 'JOHN LENNON DA SILVA SANTOS', 'a.john.santos@aec.com.br', 9, 16, 2, 3, 'I', '2025-11-13 16:24:23'),
  ('134187', 'JONATHAN LINS DA SILVA', 'jonathan.silva@aec.com.br', 3, 13, 11, 3, 'I', '2025-11-11 10:23:32'),
  ('325729', 'JORDANA KAROLLYNE SANTOS QUEIROZ', 'jordana.queiroz@aec.com.br', 8, 11, 5, 6, 'I', '2025-11-13 17:49:49'),
  ('211199', 'JULIO CESAR ALVES DA SILVA SANTOS', 'a.julio.cesar@aec.com.br', 10, 14, 4, 2, 'I', '2025-11-10 10:35:48'),
  ('227625', 'KELCIANE CAVALCANTE DE LIMA', 'kelciane.lima@aec.com.br', 11, 9, 2, 8, 'D', '2025-11-10 09:54:15'),
  ('225775', 'KELDES SILVA DE ARAUJO', 'a.keldes.araujo@aec.com.br', 7, 7, 8, 8, 'C', '2025-11-10 09:23:05'),
  ('263147', 'LETICIA SANTOS GOMES', 'a.leticia.sgomes@aec.com.br', 8, 4, 5, 13, 'C', '2025-11-11 10:42:30'),
  ('299268', 'LORRANNY WITORIA LEITE DOS SANTOS', 'a.lorranny.wsantos@aec.com.br', 9, 7, 9, 5, 'S', '2025-11-10 09:28:55'),
  ('344118', 'LUAN HENRIQUE GOMES LUCENA', 'luan.lucena@aec.com.br', 4, 9, 9, 8, 'S', '2025-11-10 09:25:13'),
  ('390247', 'LUIS HENRIQUE AMORIM DA SILVA', 'a.luis.asilva@aec.com.br', 0, 6, 14, 10, 'S', '2025-11-10 09:28:35'),
  ('307241', 'MARIA ALICE MIRANDA DA SILVA', 'maria.alice@aec.com.br', 1, 7, 13, 9, 'S', '2025-11-10 09:22:53'),
  ('157727', 'MARIA AMANDA DOS SANTOS', 'a.maria.amanda@aec.com.br', 5, 11, 11, 3, 'S', '2025-11-10 09:25:27'),
  ('225756', 'MARIA CLARA DA SILVA SANTOS', 'a.maria.clara@aec.com.br', 2, 18, 3, 7, 'I', '2025-11-13 17:25:07'),
  ('452015', 'MARIA CLARA FRANCA DA SILVA', 'maria.clfranca@aec.com.br', 7, 16, 6, 1, 'I', '2025-11-11 10:59:46'),
  ('281726', 'MARIANA PEREIRA VERAS', 'a.mariana.veras@aec.com.br', 16, 8, 3, 3, 'D', '2025-11-10 10:39:49'),
  ('238470', 'MAYENNY DE ALMEIDA SANTOS', 'a.mayenny.santos@aec.com.br', 4, 20, 3, 3, 'I', '2025-11-10 09:28:54'),
  ('461576', 'MICKAEL BANDEIRA DA SILVA', 'mickael.bandeira@aec.com.br', 16, 5, 3, 6, 'D', '2025-11-04 14:32:10'),
  ('387998', 'MIKAELLY TENORIO DA SILVA', 'mikaelly.tenorio@aec.com.br', 5, 19, 4, 2, 'I', '2025-11-10 09:31:09'),
  ('294911', 'MURILLO HENRIQUE ALMEIDA DE SOUZA', 'a.murillo.asouza@aec.com.br', 0, 11, 12, 7, 'S', '2025-11-10 09:27:25'),
  ('324648', 'MYKAELLI DARLA FRANCISCA DA SILVA', 'mykaelli.silva@aec.com.br', 5, 8, 13, 4, 'S', '2025-11-10 09:45:59'),
  ('321356', 'PALOMA CAROLINE SILVA ARAUJO', 'paloma.saraujo@aec.com.br', 10, 9, 6, 5, 'D', '2025-11-10 09:22:31'),
  ('286898', 'PAULINA INACIO GOMES NUNES', 'nu.paulina.gomes@aec.com.br', 5, 7, 7, 11, 'C', '2025-11-10 09:47:44'),
  ('333076', 'PAULO GUILHERME DOS ANJOS CASTILIANI', 'paulo.castiliani@aec.com.br', 8, 19, 3, 0, 'I', '2025-11-11 11:39:19'),
  ('417527', 'PAULO HENRIQUE TENORIO LIMA', 'paulo.tenorio@aec.com.br', 5, 13, 6, 6, 'I', '2025-11-10 09:19:54'),
  -- Rayla Alves: Pendente
  -- Renata Maria: Pendente
  ('326416', 'ROBERIO ALVES SANTANA JUNIOR', 'roberio.junior@aec.com.br', 20, 6, 0, 4, 'D', '2025-11-10 09:53:51'),
  ('359028', 'RONALDO NOBERTO DOS SANTOS', 'ronaldo.noberto@aec.com.br', 7, 10, 8, 5, 'I', '2025-11-10 10:09:39'),
  ('179844', 'SAMUEL PEDRO DOS SANTOS', 'a.samuel.pedro@aec.com.br', 11, 5, 10, 4, 'D', '2025-11-10 10:08:27'),
  -- Silvia Rafaela: Pendente
  ('268142', 'SILVIO MANUEL SILVA SANTOS', 'a.silvio.santos@aec.com.br', 2, 2, 8, 18, 'C', '2025-11-10 09:31:25'),
  ('425703', 'TAISE CORREIA DE LIRA', 'taise.lira@aec.com.br', 11, 8, 7, 4, 'D', '2025-11-10 09:27:36'),
  ('260797', 'VALDERLAN LACERDA DOS SANTOS', 'a.valderlan.santos@aec.com.br', 2, 9, 18, 1, 'S', '2025-11-10 10:00:46'),
  ('143234', 'VANESSA FERREIRA DOS SANTOS', 'a.vanessa.dsantos@aec.com.br', 9, 8, 4, 9, 'C', '2025-11-10 09:49:27'),
  ('260648', 'VINICIUS GABRIEL SILVA OLIVEIRA', 'a.vinicius.oliveira@aec.com.br', 8, 3, 2, 17, 'C', '2025-11-10 10:23:55'),
  ('314018', 'VITOR RAFAEL BARBOSA DE FARIAS', 'vitor.farias@aec.com.br', 25, 4, 0, 1, 'D', '2025-11-10 09:22:41'),
  ('306064', 'WELLINGTON NASCIMENTO DA SILVA', 'a.wellington.nsilva@aec.com.br', 1, 9, 10, 10, 'C', '2025-11-10 09:25:23'),
  ('262756', 'YARA BENEDITA DOS SANTOS SILVA', 'a.yara.ssilva@aec.com.br', 6, 4, 7, 13, 'C', '2025-11-10 09:36:42')
ON CONFLICT DO NOTHING;

-- 3. Link unlinked test results
UPDATE test_results
SET participant_id = participants.id
FROM participants
WHERE test_results.registration = participants.registration
AND test_results.participant_id IS NULL;
